name: AutoSaveWorld
main: autosaveworld.AutoSaveWorld
version: 4.7.dev-02_06_2013
author: Shevchik
load: STARTUP 
description: >
             Provides automatic world saves at defined intervals.  The focus
             of the plugin is to provide a method to flush changes to disk.
             Also provides automatic world backups. Can also purge plugins data for players 
             that are not played on server for too long
commands:
  autosaveworld:
    description: All AutoSaveWorld commands
    aliases: asw
    usage: Use /asw help  to show all commands availible in plugin.
  autosave:
    description: AutoSaveWorld /asw save command
    aliases: save
    usage: Use /save to run AutoSave
  autobackup:
    description: AutoSaveWorld /asw backup command
    aliases: backup
    usage: Use /backup to run AutoBackup
  autopurge:
    description: AutoSaveWorld /asw purge command
    aliases: purge
    usage: Use /purge to run /asw purge command