name: AutoSaveWorld
main: autosaveworld.core.AutoSaveWorld
version: 4.9.1-devel
author: _Shevchik_
load: STARTUP 
description: >
             Provides automatic world saves at defined intervals.  The focus
             of the plugin is to provide a method to flush changes to disk.
             Also provides automatic world backups. Can also purge plugins data for players 
             that are not played on server for too long
commands:
  autosaveworld:
    description: All AutoSaveWorld commands
    aliases: asw
    usage: Use /asw help  to show all commands available in plugin.
  autosave:
    description: AutoSaveWorld /asw save command
    aliases: save
    usage: Use /save to run AutoSave
  autobackup:
    description: AutoSaveWorld /asw backup command
    aliases: backup
    usage: Use /backup to run AutoBackup
  autopurge:
    description: AutoSaveWorld /asw purge command
    aliases: purge
    usage: Use /purge to run /asw purge command